Adiciona Aluno 1 na lista de alunos
inajaraleppa/pull-requests-aceleradora-2019-1 pull request #1
Opened 2019-04-15 22:07 UTC by inajaraleppa

2019-04-15 22:10 UTC, inajaraleppa commented on alunos.txt
> +Nome: Aluno 1
Sugestão: Colocar seu nome completo

2019-04-16 13:41 UTC, yrachid requested changes
por favor atualizar o nome

2019-04-16 13:48 UTC, yrachid approved these changes

2019-04-16 13:51 UTC, yrachid approved these changes

2019-04-16 13:53 UTC, merged